### ISSUE TITLE
App crash on clicking the button 

### ISSUE THREAD

**Issue by purushottam858** [rainmaker29/Android-Camera#2]
when I deploy the app on android phone with USB debugging ON and logcat , app crashes when button on screen is clicked and alot of stuff is printing from the begging and continues to print even after the crash .

I printed the ======================= when button  clicked  to identify  the  bug  . 

02-27 02:13:48.720  2313  2404 D NtpTrustedTime: currentTimeMillis() cache hit
02-27 02:13:48.728  7308  7333 I python  : ======================================================================================================================================================
02-27 02:13:48.821  2313  2404 D NtpTrustedTime: currentTimeMillis() cache hit
02-27 02:13:48.824  5459  5599 I TrafficManageService: mina mTrafficStatsReceiver onReceive

02-27 02:13:48.840  7308  7333 I python  :  Traceback (most recent call last):
02-27 02:13:48.840  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/plyer/utils.py", line 93, in _ensure_obj
02-27 02:13:48.841  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/plyer/platforms/android/camera.py", line 9, in <module>
02-27 02:13:48.841  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/jnius/reflect.py", line 208, in autoclass

02-27 02:13:48.841  7308  7333 I python  :    File "jnius/jnius_export_func.pxi", line 28, in jnius.jnius.find_javaclass
02-27 02:13:48.841  7308  7333 I python  :  jnius.jnius.JavaException: Class not found b'org/renpy/android/PythonActivity'
02-27 02:13:48.841  7308  7333 I python  : [INFO   ] [Base        ] Leaving application in progress...
02-27 02:13:48.842  7308  7333 I python  :  Traceback (most recent call last):
02-27 02:13:48.842  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/app/main.py", line 47, in <module>
02-27 02:13:48.842  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/app.py", line 855, in run
02-27 02:13:48.842  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 504, in runTouchApp
02-27 02:13:48.843  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 747, in mainloop
02-27 02:13:48.843  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 479, in _mainloop
02-27 02:13:48.843  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 342, in idle
02-27 02:13:48.844  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 327, in dispatch_input
02-27 02:13:48.844  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 233, in post_dispatch_input
02-27 02:13:48.844  7308  7333 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
02-27 02:13:48.845  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/__init__.py", line 1402, in on_motion
02-27 02:13:48.845  7308  7333 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
02-27 02:13:48.845  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/__init__.py", line 1418, in on_touch_down
02-27 02:13:48.846  7308  7333 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
02-27 02:13:48.846  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/app/main.py", line 29, in on_touch_down
02-27 02:13:48.846  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/plyer/facades/camera.py", line 64, in take_picture
02-27 02:13:48.846  7308  7333 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/plyer/facades/camera.py", line 85, in _take_picture
02-27 02:13:48.847  7308  7333 I python  :  NotImplementedError
02-27 02:13:48.847  7308  7333 I python  : Python for android ended.
02-27 02:13:48.943  2313  2389 W InputDispatcher: channel '40d696a org.test.myapp/org.kivy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-27 02:13:48.943  2313  2389 E InputDispatcher: channel '40d696a org.test.myapp/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-27 02:13:48.944  2313  3569 I ActivityManager: Process org.test.myapp (pid 7308) has died: fore TOP 
02-27 02:13:48.944  2313  7309 I WindowManager: WIN DEATH: Window{40d696a u0 org.test.myapp/org.kivy.android.PythonActivity}
02-27 02:13:48.944  2313  7309 W InputDispatcher: Attempted to unregister already unregistered input channel '40d696a org.test.myapp/org.kivy.android.PythonActivity (server)'
02-27 02:13:48.945  2313  3569 W ActivityManager: Force removing ActivityRecord{f06067b u0 org.test.myapp/org.kivy.android.PythonActivity t840}: app died, no saved state
02-27 02:13:48.946  2313  2332 W libprocessgroup: kill(-7308, 9) failed: No such process
02-27 02:13:48.950  1065  1065 I Zygote  : Process 7308 exited cleanly (255)
02-27 02:13:48.952  2313  2332 W libprocessgroup: kill(-7308, 9) failed: No such process
02-27 02:13:48.952  2313  2332 I libprocessgroup: Successfully killed process cgroup uid 10418 pid 7308 in 6ms
02-27 02:13:48.954  2510  2510 D EventBus: [2510, u0] send(AppTransitionFinishedEvent)
02-27 02:13:48.955  2510  2510 D EventBus: [2510, u0]  -> ForcedResizableInfoActivityController [0x38c9bbc, P1] onBusEvent(AppTransitionFinishedEvent)
02-27 02:13:48.955  2510  2510 D EventBus: [2510, u0] onBusEvent(AppTransitionFinishedEvent) duration: 28 microseconds, avg: 1864
02-27 02:13:48.957   795   865 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{d10bcf1 token=Token{9ac6c98 ActivityRecord{f06067b u0 org.test.myapp/org.kivy.android.PythonActivity t840}}}#0

**Comment by AshuK8s** [comment]
Same issue here it shows `NotImplementedError`..... btw there is a part in buildozer.spec file `#android.logcat_filters = *:S python:D`
Remove the `#` to see logs only from python
